-- NAVIGATE TO YOUR REPO DIRECTORY AND RUN THE FOLLOWING COMMAND FROM YOUR POSTGRES CLI
-- \i backend/database/postgreSQL/schema.sql

DROP DATABASE IF EXISTS YOUR_DATABASE_NAME;

CREATE DATABASE YOUR_DATABASE_NAME;

\c YOUR_DATABASE_NAME;

CREATE TABLE public.YOUR_TABLE_NAME (
  id SERIAL PRIMARY KEY,
  text VARCHAR(200) NOT NULL
);

CREATE TABLE public.YOUR_OTHER_TABLE_NAME (
  id SERIAL PRIMARY KEY,
  YOUR_TABLE_NAME_id INT,
);

-- // add foreign keys below

ALTER TABLE public.YOUR_OTHER_TABLE_NAME ADD CONSTRAINT fk_YOUR_OTHER_TABLE_NAME FOREIGN KEY (YOUR_TABLE_NAME_id) REFERENCES public.YOUR_TABLE_NAME(id);